### ISSUE TITLE
The npm Package is not working anymore

### ISSUE THREAD

**Issue by Franciscojose05** [tony-xlh/image-cropper-component#2]
After clicking openCropper this error occurs: 
cvr.wasm.js:1 Uncaught (in promise) RuntimeError: Aborted(Assertion failed: undefined symbol `PARAEXPORT_sDMModesArgumentsKeys`. perhaps a side module was not linked in? if this global was expected to arrive from a system library, try to build the MAIN_MODULE with EMCC_FORCE_STDLIBS=1 in the environment)
    at abort (cvr.wasm.js:1:18643)
    at assert (cvr.wasm.js:1:9597)
    at reportUndefinedSymbols (cvr.wasm.js:1:29672)
    at cvr.wasm.js:1:30402
    
    The Error is thrown in the initCVR() Method on the line 
    window["Dynamsoft"]["CVR"]["CaptureVisionRouter"].preloadModule(["DDN"]);

**Comment by xulihang** [comment]
This is caused by the release of a new version of Dynamsoft Document Normalizer. I've released a new version 2.2.0 to fix this problem.

Also, use the following to include DDN:

```html
<script src="https://cdn.jsdelivr.net/npm/dynamsoft-core@3.0.30/dist/core.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dynamsoft-license@3.0.20/dist/license.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dynamsoft-document-normalizer@2.0.20/dist/ddn.js"></script>
<script src="https://cdn.jsdelivr.net/npm/dynamsoft-capture-vision-router@2.0.30/dist/cvr.js"></script>
```

**Comment by Franciscojose05** [comment]
Hi, thanks, now it works. Ethan Tse sent me the actual new Link to the working Demo: https://dynamsoft-rd-0.github.io/ddnjs-mass-sample/image-cropper-component-with-ddn-bundle.html. Perhaps you could add it to the Readme.
I don't quite understand why the package threw an error, although the packages were not updated. 
It would be important for the npm package to work in its respective version in the future, as we want to use a fork of it in production. Thank you for your quick help.

**Comment by xulihang** [comment]
> Hi, thanks, now it works. Ethan Tse sent me the actual new Link to the working Demo: https://dynamsoft-rd-0.github.io/ddnjs-mass-sample/image-cropper-component-with-ddn-bundle.html. Perhaps you could add it to the Readme. I don't quite understand why the package threw an error, although the packages were not updated. It would be important for the npm package to work in its respective version in the future, as we want to use a fork of it in production. Thank you for your quick help.

The linked version is a temporary version to support offline license. The new updated npm package uses the official DDN JS 2.0.20 released last Friday.

**Comment by Franciscojose05** [comment]
Ah, i see. Thanks for your quick help again.
