### ISSUE TITLE
On the iPhone an error is thrown when cropping, when the photo is taken - undefined is not an object (evaluating 'normalizedImageResultItem.toCanvas')

### ISSUE THREAD

**Issue by Franciscojose05** [tony-xlh/image-cropper-component#3]
iPhone Model: XS Max - iOS 17.3
Steps:
Click select File
Take a picture with the iPhone Camera
Open Cropper
Confirm
Error:
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'normalizedImageResultItem.toCanvas')

The Error appeared with the newest Version.

Notes: I downloaded the Repo, added my license, served on Port:3334. Connected my iPhone to Mac. Served $myIP:3334 on my iPhone and checked the console on my Mac.

**Comment by Franciscojose05** [comment]
i think i found the error.
If you don’t use
templateName as parameter
in
let normalizedImagesResult:CapturedResult = await this.cvr.capture(img);
in
@Method()
async getCroppedImage(options:CropOptions):Promise<string>
 
It works just fine, even after taking the picture with the camera.

**Comment by xulihang** [comment]
This is caused by the inconsistent coordinates due to scaling down of high-resolution photos. I've released a new version 2.2.1 to fix this.
