### ISSUE TITLE
Touchevents not working on Windows Surface Tablet

### ISSUE THREAD

**Issue by Franciscojose05** [tony-xlh/image-cropper-component#4]
On a Windows Surface tablet, the corners of the cropper cannot be moved. The touch event is triggered, but the cropper does not respond to it. The issue occurs when I use the Windows Surface as a tablet. This functionality is essential for us, as most of our business customers use Windows Surface, also as a tablet.
![IMG_4764](https://github.com/tony-xlh/image-cropper-component/assets/89582136/f3e10c14-f685-43b4-b8c1-e43727d10441)

**Comment by xulihang** [comment]
I am investigating with my Windows touchscreen device. It seems that we need to use `PointerEvent`.

**Comment by xulihang** [comment]
I've released a new version 2.2.3 which works on FireFox. But it does not perform well on Chrome.

**Comment by Franciscojose05** [comment]
On chrome i get this error
<img width="1059" alt="Bildschirmfoto 2024-02-02 um 11 10 42" src="https://github.com/tony-xlh/image-cropper-component/assets/89582136/ae2a23c5-abfc-4d10-9ab8-37a1dd2b34ce">
Is your Version deployed to https://candid-tarsier-04033c.netlify.app/?

**Comment by xulihang** [comment]
It seems that the license is expired.

**Comment by Franciscojose05** [comment]
This does the trick on Chrome on Surface Tablet. You have to deactivate the standard touch action from the Browser: 
svg {
  touch-action: none; 
}
Then you can move the handler smoothly.

**Comment by xulihang** [comment]
Thanks. I've released version 2.3.0 to fix this.

**Comment by xulihang** [comment]
I've also raised an issue for stencil about using touchevents: https://github.com/ionic-team/stencil/issues/5320
