### ISSUE TITLE
If the line of the Cropper (bottom right) is slightly outside of the image, it cannot be cropped.

### ISSUE THREAD

**Issue by Franciscojose05** [tony-xlh/image-cropper-component#5]
Add an image where the bottom right corner is slightly cropped.
![img Kopie](https://github.com/tony-xlh/image-cropper-component/assets/89582136/05bfa6f9-90e2-471f-a85b-bf22130045cf)

In the getCroppedImage-Method the normalizedImagesResult.items[0] is empty and normalizedImageResultItem is undefined.
<img width="975" alt="Bildschirmfoto 2024-03-19 um 12 40 35" src="https://github.com/tony-xlh/image-cropper-component/assets/89582136/0fac82d0-346c-4b72-993e-1a50321c664f">

**Comment by Franciscojose05** [comment]
When serving this npm Package and the line is cut as shown above i get this error: 
<img width="456" alt="Bildschirmfoto 2024-03-19 um 13 00 45" src="https://github.com/tony-xlh/image-cropper-component/assets/89582136/39760374-edcd-4e49-85ab-87bc92f8c4b4">
If i move the botton right corner a little bit to the left it works:
<img width="91" alt="Bildschirmfoto 2024-03-19 um 13 03 42" src="https://github.com/tony-xlh/image-cropper-component/assets/89582136/248a25fc-8ad9-43db-8107-0acf0fb24828">

**Comment by Franciscojose05** [comment]
I think i have found a fix: Call the restrainPointsInBounds in  watchQuadPropHandler, like so ```
watchQuadPropHandler(newValue: Quad) {
    if (newValue) {
      this.usingQuad = true;
      this.points = newValue.points;
      console.log(this.points)
      this.restrainPointsInBounds(this.points, this.img.naturalWidth, this.img.naturalHeight);
    }
  } 
```and edit the restrainPointsInBounds Method like so: 
```
restrainPointsInBounds(points:[Point,Point,Point,Point],imgWidth:number,imgHeight:number){
   for (let index = 0; index < points.length; index++) {
      const point = points[index];
      point.x = Math.max(0,point.x);
      point.x = Math.min(point.x,imgWidth-10);
      point.y = Math.max(0,point.y);
      point.y = Math.min(point.y,imgHeight-10);
    }
  }
```

**Comment by xulihang** [comment]
Yes. This is a fix.

**Comment by xulihang** [comment]
I've released a new version: 2.3.1 to fix this: https://github.com/tony-xlh/image-cropper-component/compare/2.3.0...2.3.1
